import "./env"; // Load environment variables first
import { db } from "./db";
import { collections, products, banners } from "@shared/schema";
import { sql } from "drizzle-orm";

const imagePath = (name: string) => `/assets/generated_images/${name}`;

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(products);
  await db.delete(collections);
  await db.delete(banners);

  // Seed collections
  console.log("Seeding collections...");
  const collectionData = [
    {
      name: "Gift Sets",
      slug: "gift-sets",
      description: "Beautiful curated gift sets perfect for any occasion",
      image: imagePath("gift_set_collection_image.png"),
      productCount: 0,
    },
    {
      name: "Jar Candles",
      slug: "jar-candles",
      description: "Premium scented candles in elegant glass jars",
      image: imagePath("jar_candles_collection.png"),
      productCount: 0,
    },
    {
      name: "Home Decor",
      slug: "home-decor",
      description: "Stylish decor pieces to enhance your living space",
      image: imagePath("home_decor_collection.png"),
      productCount: 0,
    },
    {
      name: "Seasonal",
      slug: "seasonal",
      description: "Limited edition seasonal fragrances for every time of year",
      image: imagePath("seasonal_collection.png"),
      productCount: 0,
    },
    {
      name: "Wellness & Spa",
      slug: "wellness-spa",
      description: "Relaxing aromatherapy candles for self-care and wellness",
      image: imagePath("wellness_spa_collection.png"),
      productCount: 0,
    },
    {
      name: "Luxury Collection",
      slug: "luxury-collection",
      description: "Premium handcrafted candles with exotic fragrances",
      image: imagePath("luxury_collection.png"),
      productCount: 0,
    },
  ];

  const insertedCollections = await db.insert(collections).values(collectionData).returning();
  console.log(`Inserted ${insertedCollections.length} collections`);

  const collectionMap = insertedCollections.reduce((acc, col) => {
    acc[col.slug] = col.id;
    return acc;
  }, {} as Record<string, number>);

  // Seed products
  console.log("Seeding products...");
  const productData = [
    // Jar Candles
    {
      name: "Amber Woods Candle",
      slug: "amber-woods-candle",
      price: 899,
      salePrice: 699,
      image: imagePath("product_candle_amber_jar.png"),
      category: "jar-candles",
      description: "A warm, woody fragrance with notes of sandalwood and amber. Perfect for cozy evenings at home.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Lavender Dreams",
      slug: "lavender-dreams",
      price: 799,
      salePrice: null,
      image: imagePath("product_candle_lavender.png"),
      category: "jar-candles",
      description: "Calming lavender essence for peaceful relaxation. Ideal for meditation and bedtime rituals.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Rose Garden",
      slug: "rose-garden",
      price: 849,
      salePrice: 749,
      image: imagePath("product_candle_rose.png"),
      category: "jar-candles",
      description: "Romantic floral notes of fresh roses and petals. A timeless fragrance for any room.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Vanilla Bliss",
      slug: "vanilla-bliss",
      price: 699,
      salePrice: null,
      image: imagePath("product_candle_vanilla.png"),
      category: "jar-candles",
      description: "Sweet and comforting vanilla fragrance. A classic scent loved by everyone.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Ocean Breeze",
      slug: "ocean-breeze",
      price: 849,
      salePrice: null,
      image: imagePath("ocean_breeze_candle.png"),
      category: "jar-candles",
      description: "Fresh coastal fragrance with sea salt and driftwood notes. Transport yourself to a serene beach.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Honey Almond",
      slug: "honey-almond",
      price: 749,
      salePrice: null,
      image: imagePath("honey_almond_candle.png"),
      category: "jar-candles",
      description: "Sweet and nutty fragrance of natural honey and toasted almonds.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Mango Paradise",
      slug: "mango-paradise",
      price: 849,
      salePrice: 699,
      image: imagePath("mango_paradise_candle.png"),
      category: "jar-candles",
      description: "Exotic tropical mango fragrance that brings summer vibes all year round.",
      inStock: true,
      isNew: false,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Coffee Mocha",
      slug: "coffee-mocha",
      price: 799,
      salePrice: null,
      image: imagePath("coffee_mocha_candle.png"),
      category: "jar-candles",
      description: "Rich coffee and chocolate fragrance for coffee lovers. Wake up to this delicious scent.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Peony Blossom",
      slug: "peony-blossom",
      price: 899,
      salePrice: 749,
      image: imagePath("peony_blossom_candle.png"),
      category: "jar-candles",
      description: "Romantic and feminine peony fragrance with soft floral notes.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Coconut Lime",
      slug: "coconut-lime",
      price: 799,
      salePrice: null,
      image: imagePath("coconut_lime_candle.png"),
      category: "jar-candles",
      description: "Tropical blend of creamy coconut and zesty lime for beach vibes.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Cotton Candy Dreams",
      slug: "cotton-candy-dreams",
      price: 699,
      salePrice: null,
      image: imagePath("cotton_candy_candle.png"),
      category: "jar-candles",
      description: "Sweet and playful cotton candy fragrance that brings joy to any room.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Bergamot Citrus",
      slug: "bergamot-citrus",
      price: 849,
      salePrice: null,
      image: imagePath("bergamot_citrus_candle.png"),
      category: "jar-candles",
      description: "Fresh Italian bergamot with bright citrus notes. Uplifting and refreshing.",
      inStock: true,
      isNew: false,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Jasmine Nights",
      slug: "jasmine-nights",
      price: 849,
      salePrice: null,
      image: imagePath("jasmine_nights_candle.png"),
      category: "jar-candles",
      description: "Intoxicating jasmine fragrance that blooms at night. Exotic and sensual.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["jar-candles"],
    },
    {
      name: "Sandalwood Serenity",
      slug: "sandalwood-serenity",
      price: 949,
      salePrice: 799,
      image: imagePath("sandalwood_serenity_candle.png"),
      category: "jar-candles",
      description: "Rich sandalwood essence for a grounding and calming atmosphere.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["jar-candles"],
    },
    // Gift Sets
    {
      name: "Lavender Gift Set",
      slug: "lavender-gift-set",
      price: 1999,
      salePrice: 1599,
      image: imagePath("lavender_gift_set.png"),
      category: "gift-sets",
      description: "Beautiful gift set featuring lavender candle, room spray, and bath salts.",
      inStock: true,
      isNew: true,
      isBestSeller: true,
      collectionId: collectionMap["gift-sets"],
    },
    {
      name: "Premium Gift Box",
      slug: "premium-gift-box",
      price: 2999,
      salePrice: 2499,
      image: imagePath("premium_gift_box.png"),
      category: "gift-sets",
      description: "Luxury gift box with 4 scented candles and decorative holder.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["gift-sets"],
    },
    {
      name: "Vanilla Mini Set",
      slug: "vanilla-mini-set",
      price: 499,
      salePrice: null,
      image: imagePath("vanilla_mini_set.png"),
      category: "gift-sets",
      description: "Mini candle set perfect for gifting. Includes 3 vanilla scented votives.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["gift-sets"],
    },
    {
      name: "Rose Gold Gift Set",
      slug: "rose-gold-gift-set",
      price: 2499,
      salePrice: 1999,
      image: imagePath("rose_gold_gift_set.png"),
      category: "gift-sets",
      description: "Luxurious gift set featuring 3 premium candles in elegant rose gold packaging.",
      inStock: true,
      isNew: true,
      isBestSeller: true,
      collectionId: collectionMap["gift-sets"],
    },
    {
      name: "Spa Wellness Set",
      slug: "spa-wellness-set",
      price: 2999,
      salePrice: null,
      image: imagePath("spa_wellness_gift_set.png"),
      category: "gift-sets",
      description: "Complete relaxation set with eucalyptus candle, bath salts, and aromatherapy oils.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["gift-sets"],
    },
    {
      name: "Couples Romance Set",
      slug: "couples-romance-set",
      price: 1799,
      salePrice: 1499,
      image: imagePath("couples_romantic_gift_set.png"),
      category: "gift-sets",
      description: "Romantic gift set with two matching candles in beautiful heart-shaped box.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["gift-sets"],
    },
    {
      name: "Wax Melts Variety Pack",
      slug: "wax-melts-variety-pack",
      price: 899,
      salePrice: 699,
      image: imagePath("wax_melts_gift_set.png"),
      category: "gift-sets",
      description: "Assorted wax melts gift set with 12 different fragrances to explore.",
      inStock: true,
      isNew: false,
      isBestSeller: false,
      collectionId: collectionMap["gift-sets"],
    },
    // Home Decor
    {
      name: "Rose Ceramic Holder",
      slug: "rose-ceramic-holder",
      price: 599,
      salePrice: null,
      image: imagePath("rose_ceramic_holder.png"),
      category: "home-decor",
      description: "Elegant ceramic candle holder with rose motif. Perfect for tea lights.",
      inStock: true,
      isNew: false,
      isBestSeller: false,
      collectionId: collectionMap["home-decor"],
    },
    {
      name: "Decorative Tray Set",
      slug: "decorative-tray-set",
      price: 899,
      salePrice: null,
      image: imagePath("decorative_tray_set.png"),
      category: "home-decor",
      description: "Beautiful tray set for displaying your candle collection.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["home-decor"],
    },
    {
      name: "Geometric Candle Holder",
      slug: "geometric-candle-holder",
      price: 1299,
      salePrice: null,
      image: imagePath("geometric_holder_set.png"),
      category: "home-decor",
      description: "Modern geometric candle holder set in brass and marble. Contemporary elegance.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["home-decor"],
    },
    {
      name: "Wall Sconce Holder",
      slug: "wall-sconce-holder",
      price: 999,
      salePrice: 799,
      image: imagePath("wall_sconce_holder.png"),
      category: "home-decor",
      description: "Elegant antique brass wall sconce for candles. Vintage charm for your walls.",
      inStock: true,
      isNew: false,
      isBestSeller: false,
      collectionId: collectionMap["home-decor"],
    },
    {
      name: "Luxury Reed Diffuser",
      slug: "luxury-reed-diffuser",
      price: 1199,
      salePrice: null,
      image: imagePath("reed_diffuser_set.png"),
      category: "home-decor",
      description: "Premium reed diffuser with essential oils for continuous home fragrance.",
      inStock: true,
      isNew: true,
      isBestSeller: true,
      collectionId: collectionMap["home-decor"],
    },
    // Seasonal
    {
      name: "Cinnamon Spice",
      slug: "cinnamon-spice",
      price: 799,
      salePrice: 649,
      image: imagePath("cinnamon_spice_candle.png"),
      category: "seasonal",
      description: "Warm and inviting cinnamon fragrance perfect for cozy autumn evenings.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["seasonal"],
    },
    {
      name: "Pine Forest",
      slug: "pine-forest",
      price: 849,
      salePrice: null,
      image: imagePath("pine_forest_candle.png"),
      category: "seasonal",
      description: "Woodsy pine and cedar fragrance reminiscent of a walk through the forest.",
      inStock: true,
      isNew: false,
      isBestSeller: false,
      collectionId: collectionMap["seasonal"],
    },
    {
      name: "Cranberry Orange",
      slug: "cranberry-orange",
      price: 899,
      salePrice: 749,
      image: imagePath("cranberry_orange_candle.png"),
      category: "seasonal",
      description: "Festive holiday blend of tart cranberry and sweet orange. Perfect for celebrations.",
      inStock: true,
      isNew: true,
      isBestSeller: true,
      collectionId: collectionMap["seasonal"],
    },
    // Wellness & Spa
    {
      name: "Eucalyptus Mint",
      slug: "eucalyptus-mint",
      price: 899,
      salePrice: null,
      image: imagePath("eucalyptus_mint_candle.png"),
      category: "wellness-spa",
      description: "Refreshing blend of eucalyptus and mint for a spa-like experience at home.",
      inStock: true,
      isNew: true,
      isBestSeller: true,
      collectionId: collectionMap["wellness-spa"],
    },
    {
      name: "Chamomile Tea",
      slug: "chamomile-tea",
      price: 899,
      salePrice: null,
      image: imagePath("chamomile_tea_candle.png"),
      category: "wellness-spa",
      description: "Calming chamomile tea fragrance for peaceful relaxation and better sleep.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["wellness-spa"],
    },
    {
      name: "Lemongrass Ginger",
      slug: "lemongrass-ginger",
      price: 849,
      salePrice: null,
      image: imagePath("lemongrass_ginger_candle.png"),
      category: "wellness-spa",
      description: "Energizing citrus blend with zesty lemongrass and spicy ginger.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["wellness-spa"],
    },
    {
      name: "White Tea & Sage",
      slug: "white-tea-sage",
      price: 899,
      salePrice: null,
      image: imagePath("white_tea_sage_candle.png"),
      category: "wellness-spa",
      description: "Subtle and sophisticated blend of white tea and fresh sage leaves.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["wellness-spa"],
    },
    // Luxury Collection
    {
      name: "Oud & Saffron",
      slug: "oud-saffron",
      price: 1499,
      salePrice: 1299,
      image: imagePath("oud_saffron_candle.png"),
      category: "luxury-collection",
      description: "Luxurious Middle Eastern inspired fragrance with rich oud and precious saffron.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["luxury-collection"],
    },
    {
      name: "Black Orchid",
      slug: "black-orchid",
      price: 1299,
      salePrice: null,
      image: imagePath("black_orchid_candle.png"),
      category: "luxury-collection",
      description: "Mysterious and elegant black orchid fragrance for sophisticated spaces.",
      inStock: true,
      isNew: false,
      isBestSeller: true,
      collectionId: collectionMap["luxury-collection"],
    },
    {
      name: "Midnight Jasmine",
      slug: "midnight-jasmine",
      price: 949,
      salePrice: null,
      image: imagePath("jasmine_nights_candle.png"),
      category: "luxury-collection",
      description: "Exotic night-blooming jasmine with hints of musk. Sensual and mysterious.",
      inStock: true,
      isNew: true,
      isBestSeller: false,
      collectionId: collectionMap["luxury-collection"],
    },
  ];

  const insertedProducts = await db.insert(products).values(productData).returning();
  console.log(`Inserted ${insertedProducts.length} products`);

  // Update collection product counts
  for (const slug of Object.keys(collectionMap)) {
    await db.execute(sql`
      UPDATE collections 
      SET product_count = (SELECT COUNT(*) FROM products WHERE category = ${slug})
      WHERE slug = ${slug}
    `);
  }
  console.log("Updated collection product counts");

  // Seed banners
  console.log("Seeding banners...");
  const bannerData = [
    {
      title: "Transform Your Space",
      subtitle: "Discover our collection of premium scented candles and home decor",
      ctaText: "Shop Now",
      ctaLink: "/shop",
      image: imagePath("hero_banner_candles_lifestyle.png"),
      type: "hero",
      isActive: true,
      sortOrder: 1,
    },
    {
      title: "Festive Season Sale",
      subtitle: "Up to 30% off on select gift sets",
      ctaText: "Explore Offers",
      ctaLink: "/sale",
      image: imagePath("diwali_festival_banner.png"),
      type: "promotional",
      isActive: true,
      sortOrder: 1,
    },
    {
      title: "New Arrivals",
      subtitle: "Discover our latest fragrances",
      ctaText: "Shop New",
      ctaLink: "/new-arrivals",
      image: imagePath("jar_candles_collection.png"),
      type: "promotional",
      isActive: true,
      sortOrder: 2,
    },
  ];

  const insertedBanners = await db.insert(banners).values(bannerData).returning();
  console.log(`Inserted ${insertedBanners.length} banners`);

  console.log("Seeding complete!");
}

seed()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Seeding failed:", error);
    process.exit(1);
  });
